// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

package com.github.myibu.proto.protos;

public final class SimpleProto {
  private SimpleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InnerIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.InnerId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  int32 id2 = 2;
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();
  }
  /**
   * Protobuf type {@code tutorial.InnerId}
   */
  public static final class InnerId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.InnerId)
      InnerIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerId.newBuilder() to construct.
    private InnerId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerId() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InnerId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_InnerId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_InnerId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.myibu.proto.protos.SimpleProto.InnerId.class, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *  int32 id2 = 2;
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.myibu.proto.protos.SimpleProto.InnerId)) {
        return super.equals(obj);
      }
      com.github.myibu.proto.protos.SimpleProto.InnerId other = (com.github.myibu.proto.protos.SimpleProto.InnerId) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myibu.proto.protos.SimpleProto.InnerId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.myibu.proto.protos.SimpleProto.InnerId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.InnerId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.InnerId)
        com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_InnerId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_InnerId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.myibu.proto.protos.SimpleProto.InnerId.class, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder.class);
      }

      // Construct using com.github.myibu.proto.protos.SimpleProto.InnerId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_InnerId_descriptor;
      }

      @java.lang.Override
      public com.github.myibu.proto.protos.SimpleProto.InnerId getDefaultInstanceForType() {
        return com.github.myibu.proto.protos.SimpleProto.InnerId.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.myibu.proto.protos.SimpleProto.InnerId build() {
        com.github.myibu.proto.protos.SimpleProto.InnerId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.myibu.proto.protos.SimpleProto.InnerId buildPartial() {
        com.github.myibu.proto.protos.SimpleProto.InnerId result = new com.github.myibu.proto.protos.SimpleProto.InnerId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.myibu.proto.protos.SimpleProto.InnerId) {
          return mergeFrom((com.github.myibu.proto.protos.SimpleProto.InnerId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.myibu.proto.protos.SimpleProto.InnerId other) {
        if (other == com.github.myibu.proto.protos.SimpleProto.InnerId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.myibu.proto.protos.SimpleProto.InnerId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.myibu.proto.protos.SimpleProto.InnerId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *  int32 id2 = 2;
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *  int32 id2 = 2;
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  int32 id2 = 2;
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.InnerId)
    }

    // @@protoc_insertion_point(class_scope:tutorial.InnerId)
    private static final com.github.myibu.proto.protos.SimpleProto.InnerId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.myibu.proto.protos.SimpleProto.InnerId();
    }

    public static com.github.myibu.proto.protos.SimpleProto.InnerId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InnerId>
        PARSER = new com.google.protobuf.AbstractParser<InnerId>() {
      @java.lang.Override
      public InnerId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InnerId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.myibu.proto.protos.SimpleProto.InnerId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Simple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    java.util.List<com.github.myibu.proto.protos.SimpleProto.InnerId> 
        getIdList();
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    com.github.myibu.proto.protos.SimpleProto.InnerId getId(int index);
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    int getIdCount();
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    java.util.List<? extends com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder> 
        getIdOrBuilderList();
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder getIdOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tutorial.Simple}
   */
  public static final class Simple extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Simple)
      SimpleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Simple.newBuilder() to construct.
    private Simple(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Simple() {
      id_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Simple();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Simple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                id_ = new java.util.ArrayList<com.github.myibu.proto.protos.SimpleProto.InnerId>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(
                  input.readMessage(com.github.myibu.proto.protos.SimpleProto.InnerId.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_Simple_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_Simple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.myibu.proto.protos.SimpleProto.Simple.class, com.github.myibu.proto.protos.SimpleProto.Simple.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 3;
    private java.util.List<com.github.myibu.proto.protos.SimpleProto.InnerId> id_;
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.github.myibu.proto.protos.SimpleProto.InnerId> getIdList() {
      return id_;
    }
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder> 
        getIdOrBuilderList() {
      return id_;
    }
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    @java.lang.Override
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    @java.lang.Override
    public com.github.myibu.proto.protos.SimpleProto.InnerId getId(int index) {
      return id_.get(index);
    }
    /**
     * <pre>
     *  map&lt;int32, float&gt; fieldMap = 1;
     *  InnerId innerId1 = 1;
     *  InnerId innerId2 = 2;
     * </pre>
     *
     * <code>repeated .tutorial.InnerId id = 3;</code>
     */
    @java.lang.Override
    public com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder getIdOrBuilder(
        int index) {
      return id_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < id_.size(); i++) {
        output.writeMessage(3, id_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < id_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, id_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.myibu.proto.protos.SimpleProto.Simple)) {
        return super.equals(obj);
      }
      com.github.myibu.proto.protos.SimpleProto.Simple other = (com.github.myibu.proto.protos.SimpleProto.Simple) obj;

      if (!getIdList()
          .equals(other.getIdList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myibu.proto.protos.SimpleProto.Simple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.myibu.proto.protos.SimpleProto.Simple prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Simple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Simple)
        com.github.myibu.proto.protos.SimpleProto.SimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_Simple_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_Simple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.myibu.proto.protos.SimpleProto.Simple.class, com.github.myibu.proto.protos.SimpleProto.Simple.Builder.class);
      }

      // Construct using com.github.myibu.proto.protos.SimpleProto.Simple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          idBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.myibu.proto.protos.SimpleProto.internal_static_tutorial_Simple_descriptor;
      }

      @java.lang.Override
      public com.github.myibu.proto.protos.SimpleProto.Simple getDefaultInstanceForType() {
        return com.github.myibu.proto.protos.SimpleProto.Simple.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.myibu.proto.protos.SimpleProto.Simple build() {
        com.github.myibu.proto.protos.SimpleProto.Simple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.myibu.proto.protos.SimpleProto.Simple buildPartial() {
        com.github.myibu.proto.protos.SimpleProto.Simple result = new com.github.myibu.proto.protos.SimpleProto.Simple(this);
        int from_bitField0_ = bitField0_;
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            id_ = java.util.Collections.unmodifiableList(id_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.myibu.proto.protos.SimpleProto.Simple) {
          return mergeFrom((com.github.myibu.proto.protos.SimpleProto.Simple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.myibu.proto.protos.SimpleProto.Simple other) {
        if (other == com.github.myibu.proto.protos.SimpleProto.Simple.getDefaultInstance()) return this;
        if (idBuilder_ == null) {
          if (!other.id_.isEmpty()) {
            if (id_.isEmpty()) {
              id_ = other.id_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIdIsMutable();
              id_.addAll(other.id_);
            }
            onChanged();
          }
        } else {
          if (!other.id_.isEmpty()) {
            if (idBuilder_.isEmpty()) {
              idBuilder_.dispose();
              idBuilder_ = null;
              id_ = other.id_;
              bitField0_ = (bitField0_ & ~0x00000001);
              idBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIdFieldBuilder() : null;
            } else {
              idBuilder_.addAllMessages(other.id_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.myibu.proto.protos.SimpleProto.Simple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.myibu.proto.protos.SimpleProto.Simple) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.github.myibu.proto.protos.SimpleProto.InnerId> id_ =
        java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          id_ = new java.util.ArrayList<com.github.myibu.proto.protos.SimpleProto.InnerId>(id_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.myibu.proto.protos.SimpleProto.InnerId, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder, com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder> idBuilder_;

      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public java.util.List<com.github.myibu.proto.protos.SimpleProto.InnerId> getIdList() {
        if (idBuilder_ == null) {
          return java.util.Collections.unmodifiableList(id_);
        } else {
          return idBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public int getIdCount() {
        if (idBuilder_ == null) {
          return id_.size();
        } else {
          return idBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public com.github.myibu.proto.protos.SimpleProto.InnerId getId(int index) {
        if (idBuilder_ == null) {
          return id_.get(index);
        } else {
          return idBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder setId(
          int index, com.github.myibu.proto.protos.SimpleProto.InnerId value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdIsMutable();
          id_.set(index, value);
          onChanged();
        } else {
          idBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder setId(
          int index, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder builderForValue) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.set(index, builderForValue.build());
          onChanged();
        } else {
          idBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder addId(com.github.myibu.proto.protos.SimpleProto.InnerId value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdIsMutable();
          id_.add(value);
          onChanged();
        } else {
          idBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder addId(
          int index, com.github.myibu.proto.protos.SimpleProto.InnerId value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIdIsMutable();
          id_.add(index, value);
          onChanged();
        } else {
          idBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder addId(
          com.github.myibu.proto.protos.SimpleProto.InnerId.Builder builderForValue) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.add(builderForValue.build());
          onChanged();
        } else {
          idBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder addId(
          int index, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder builderForValue) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.add(index, builderForValue.build());
          onChanged();
        } else {
          idBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<? extends com.github.myibu.proto.protos.SimpleProto.InnerId> values) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, id_);
          onChanged();
        } else {
          idBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          idBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public Builder removeId(int index) {
        if (idBuilder_ == null) {
          ensureIdIsMutable();
          id_.remove(index);
          onChanged();
        } else {
          idBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public com.github.myibu.proto.protos.SimpleProto.InnerId.Builder getIdBuilder(
          int index) {
        return getIdFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder getIdOrBuilder(
          int index) {
        if (idBuilder_ == null) {
          return id_.get(index);  } else {
          return idBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public java.util.List<? extends com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder> 
           getIdOrBuilderList() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(id_);
        }
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public com.github.myibu.proto.protos.SimpleProto.InnerId.Builder addIdBuilder() {
        return getIdFieldBuilder().addBuilder(
            com.github.myibu.proto.protos.SimpleProto.InnerId.getDefaultInstance());
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public com.github.myibu.proto.protos.SimpleProto.InnerId.Builder addIdBuilder(
          int index) {
        return getIdFieldBuilder().addBuilder(
            index, com.github.myibu.proto.protos.SimpleProto.InnerId.getDefaultInstance());
      }
      /**
       * <pre>
       *  map&lt;int32, float&gt; fieldMap = 1;
       *  InnerId innerId1 = 1;
       *  InnerId innerId2 = 2;
       * </pre>
       *
       * <code>repeated .tutorial.InnerId id = 3;</code>
       */
      public java.util.List<com.github.myibu.proto.protos.SimpleProto.InnerId.Builder> 
           getIdBuilderList() {
        return getIdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.myibu.proto.protos.SimpleProto.InnerId, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder, com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.myibu.proto.protos.SimpleProto.InnerId, com.github.myibu.proto.protos.SimpleProto.InnerId.Builder, com.github.myibu.proto.protos.SimpleProto.InnerIdOrBuilder>(
                  id_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Simple)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Simple)
    private static final com.github.myibu.proto.protos.SimpleProto.Simple DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.myibu.proto.protos.SimpleProto.Simple();
    }

    public static com.github.myibu.proto.protos.SimpleProto.Simple getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Simple>
        PARSER = new com.google.protobuf.AbstractParser<Simple>() {
      @java.lang.Override
      public Simple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Simple(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Simple> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Simple> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.myibu.proto.protos.SimpleProto.Simple getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_InnerId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_InnerId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Simple_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Simple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014simple.proto\022\010tutorial\"\025\n\007InnerId\022\n\n\002i" +
      "d\030\001 \001(\005\"\'\n\006Simple\022\035\n\002id\030\003 \003(\0132\021.tutorial" +
      ".InnerIdB,\n\035com.github.myibu.proto.proto" +
      "sB\013SimpleProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_InnerId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_InnerId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_InnerId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_tutorial_Simple_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Simple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Simple_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
